package snage.up.laaco

class QuestionList {
    val questions = listOf(
        Question("What is the most popular sport in the world?", "Soccer", "Basketball", "Tennis", "Football", 4),
        Question("Which country is known as the \"Home of Cricket\"?", "Australia", "England", "India", "South Africa", 2),
        Question("How many players are on a standard soccer team?", "9", "10", "11", "12", 3),
        Question("Which athlete has won the most Olympic gold medals?", "Michael Phelps", "Usain Bolt", "Michael Johnson", "Jesse Owens", 1),
        Question("What is the object used in golf to hit the ball?", "Paddle", "Club", "Bat", "Stick", 2),
        Question("In which sport can you perform a slam dunk?", "Volleyball", "Hockey", "Baseball", "Basketball", 4),
        Question("What is the highest score possible in a single turn in bowling?", "10", "100", "300", "500", 3),
        Question("Which country won the first World Cup in cricket?", "Australia", "England", "India", "West Indies", 2),
        Question("How many Grand Slam titles does Rafael Nadal have?", "10", "15", "20", "25", 3),
        Question("Which horse has won the most Kentucky Derbies?", "Secretariat", "Black Beauty", "Silverado", "Seabiscuit", 1),
        Question("Which team has won the most Super Bowls in NFL history?", "Dallas Cowboys", "Pittsburgh Steelers", "San Francisco 49ers", "New England Patriots", 2),
        Question("Which player is often referred to as the \"Black Mamba\"?", "LeBron James", "Kobe Bryant", "Michael Jordan", "Magic Johnson", 2),
        Question("Which country won the FIFA World Cup in 2018?", "France", "Germany", "Brazil", "Argentina", 1),
        Question("Which sport uses the term \"Love\" to represent zero?", "Tennis", "Soccer", "Cricket", "Golf", 1),
        Question("In which city are the Summer Olympics 2020 scheduled to be held?", "London", "Paris", "Tokyo", "Rio de Janeiro", 3),
        Question("Which sport is known as the \"King of Sports\"?", "Soccer", "Rugby", "Cricket", "Tennis", 3),
        Question("Which boxer is famous for the phrase \"Float like a butterfly, sting like a bee\"?", "Mike Tyson", "Floyd Mayweather Jr.", "Muhammad Ali", "Manny Pacquiao", 3),
        Question("Which city hosted the Winter Olympics in 2014?", "Vancouver", "Sochi", "Pyeongchang", "Salt Lake City", 2),
        Question("Which female tennis player has won the most Grand Slam singles titles?", "Serena Williams", "Steffi Graf", "Martina Navratilova", "Maria Sharapova", 1),
        Question("Which sport is associated with Wembley Stadium?", "Soccer", "Rugby", "Cricket", "Tennis", 1),
        Question("Which country won the most medals in the 2016 Summer Olympics?", "China", "United States", "Russia", "Great Britain", 2),
        Question("Which NBA player is known as \"The Greek Freak\"?", "Kobe Bryant", "LeBron James", "Stephen Curry", "Giannis Antetokounmpo", 4),
        Question("Which country won the first FIFA World Cup in 1930?", "Uruguay", "Brazil", "Italy", "Argentina", 1),
        Question("In which year was the first modern Olympic Games held?", "1886", "1896", "1906", "1916", 2),
        Question("Which sport has a field called a \"pitch\"?", "Baseball", "Soccer", "Football", "Basketball", 2),
        Question("Which American sprinter won four gold medals at the 1936 Berlin Olympics?", "Carl Lewis", "Jesse Owens", "Usain Bolt", "Michael Johnson", 2),
        Question("Which sport uses a shuttlecock?", "Tennis", "Badminton", "Table Tennis", "Volleyball", 2),
        Question("Which country is known for its dominant performance in cricket's \"Ashes\" series?", "Australia", "England", "South Africa", "India", 1),
        Question("How many players are there on a standard ice hockey team?", "5", "6", "7", "8", 2),
        Question("Who holds the record for the most home runs in Major League Baseball?", "Barry Bonds", "Babe Ruth", "Hank Aaron", "Alex Rodriguez", 1),
        Question("Which country has won the most FIFA World Cup titles?", "Italy", "Brazil", "Germany", "France", 2),
        Question("What is the smallest scoring unit in American football?", "Point", "Goal", "Yard", "Touchdown", 4),
        Question("Which sport uses the terms \"strike\" and \"spare\"?", "Tennis", "Golf", "Bowling", "Soccer", 3),
        Question("Which country won the Rugby World Cup in 2019?", "South Africa", "New Zealand", "Australia", "England", 1),
        Question("Which player is often referred to as \"The Great One\" in ice hockey?", "Sidney Crosby", "Wayne Gretzky", "Mario Lemieux", "Alex Ovechkin", 2),
        Question("In which year was the first Wimbledon Championship held?", "1877", "1896", "1903", "1921", 1),
        Question("What is the scoring term used in golf when a player completes a hole with one stroke under par?", "Eagle", "Birdie", "Par", "Bogey", 2),
        Question("Which country won the UEFA European Championship in 2016?", "Spain", "France", "Germany", "Portugal", 4),
        Question("Which sport uses a round ball and a small white ball called the \"jack\"?", "Bowling", "Curling", "Bocce", "Croquet", 3),
        Question("In which city did the Summer Olympics take place in 2016?", "London", "Beijing", "Rio de Janeiro", "Tokyo", 3),
        Question("Which NBA team won the most championships in the 1990s?", "Chicago Bulls", "Los Angeles Lakers", "Boston Celtics", "Houston Rockets", 1),
        Question("Which country is known for producing Formula One racing drivers Ayrton Senna and Felipe Massa?", "Italy", "Brazil", "Germany", "France", 2),
        Question("What is the longest race in the Olympic track and field events?", "100 meters", "200 meters", "400 meters", "Marathon", 4), Question("Which country has won the most medals in the Winter Olympics?", "Norway", "United States", "Germany", "Canada", 1),
        Question("Which player is often referred to as the \"Wizard of Westwood\"?", "Larry Bird", "Michael Jordan", "Magic Johnson", "John Wooden", 4),
        Question("In American football, how many points is a touchdown worth?", "3", "5", "6", "7", 3),
        Question("Which country won the first ICC T20 World Cup?", "India", "England", "Pakistan", "South Africa", 3),
        Question("How many Grand Slam singles titles does Serena Williams hold?", "15", "20", "23", "28", 3),
        Question("Which sport is played on a rink?", "Soccer", "Basketball", "Hockey", "Baseball", 3),
        Question("Which country has won the most gold medals in the Summer Olympics?", "United States", "China", "Russia", "Germany", 1)
    )
}